### ISSUE TITLE
decode_seqs to disk fails

### ISSUE THREAD

**Issue by dvdrndlph** [uzh-dqbm-cmi/PySeqLab#1]
(Thanks for this excellent project. It promises to save me a lot of work. I will try to fix this issue on my own fork.)

The results returned  by pyseqlab.utilities.decode_seqs() look good, but I see an error when I try to direct the results to disk.

That is,

`decoded_sequences = model.decode_seqs(decoding_method, output_dir, seqs=test_seqs, sep=sep)`

looks good, but

`decoded_sequences = model.decode_seqs(decoding_method, output_dir, seqs=test_seqs, file_name='decoding.txt', sep=sep)`

throws this error:

> Traceback (most recent call last):
  File "/Users/dave/tb2/pydactyl/bin/crf_psl.py", line 248, in <module>
    evaluate_trained_model(ex=ex, experiment_name=experiment_name, model_dir=model_dir)
  File "/Users/dave/tb2/pydactyl/bin/crf_psl.py", line 219, in evaluate_trained_model
    decoded_sequences = model.decode_seqs(decoding_method, output_dir, seqs=test_seqs,
  File "/Users/dave/tb2/PySeqLab/pyseqlab/linear_chain_crf.py", line 1074, in decode_seqs
    self.write_decoded_seqs([seq], [Y_pred], out_file, sep)
  File "/Users/dave/tb2/PySeqLab/pyseqlab/linear_chain_crf.py", line 1102, in write_decoded_seqs
    line += ref_seq.X[t][field_name] + sep
TypeError: unsupported operand type(s) for +: 'int' and 'str'

It also seems wrong that the out_dir parameter is required. Some callers will only want the returned data structure and don't want to write the results anywhere.

**Comment by orisenbazuru** [comment]
Thank you for your kind words.  Regarding the issue, I think it is a concatenation issue. Most probably the feature saved in `ref_seq.X[t][field_name]` is not casted to `string` when concatenated with the `sep`(by default the `sep="\t"`).  A quick fix would be to update the line in https://github.com/uzh-dqbm-cmi/PySeqLab/blob/d9e37a0f8f773f61d9886223878c84b8b0921696/pyseqlab/linear_chain_crf.py#L1102 by changing it to 
```python
line += str(ref_seq.X[t][field_name]) + sep
```
or 
```python
line += f"{ref_seq.X[t][field_name]}{sep}"
```

Regarding the `out_dir`, by default (or by design) is to process sequences and dump them on disk (this typically includes the features generated for each sequence and other relevant info) such that you do not need to hold things in memory. This would allow you to scale and process large number of sequences even on a modest device without risking to have insufficient memory etc.  Obviously you can do this differently and have a different design strategy such that to keep things in memory (but this was not the case when developing the package). In both cases, the results (decoded sequences) are returned as dictionary and would not be written on disk unless you specify a `file_name`.

Let me know if this works so that I can update the repo at a later point.

Thank you.

**Comment by dvdrndlph** [comment]
This looks like a good fix.

I am not that concerned with the no non-use of out_dir. It still seems like it should not be required, but this is not a big deal.

Thanks for the background on memory usage. I do see an enormous amount if disk I/O in my runs, but I am staying under 8GB of RAM. As it stands, I currently have access to machines with over half a terabyte of RAM. It would be nice if I could make use of this memory to speed things up somehow. I looked into RAM disks, but they look a little dangerous on multi-user systems. Anyway, I am just auditioning features with sklearn-crfsuit, and then using your invaluable tool for the higher order CRFs.

Thanks again for all this great work.
